//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDPlayer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MDPlayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap addFolderPL {
            get {
                object obj = ResourceManager.GetObject("addFolderPL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap addPL {
            get {
                object obj = ResourceManager.GetObject("addPL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ccFadeout {
            get {
                object obj = ResourceManager.GetObject("ccFadeout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ccFast {
            get {
                object obj = ResourceManager.GetObject("ccFast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ccNext {
            get {
                object obj = ResourceManager.GetObject("ccNext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ccPause {
            get {
                object obj = ResourceManager.GetObject("ccPause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ccPlay {
            get {
                object obj = ResourceManager.GetObject("ccPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ccPrevious {
            get {
                object obj = ResourceManager.GetObject("ccPrevious", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ccSlow {
            get {
                object obj = ResourceManager.GetObject("ccSlow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ccStop {
            get {
                object obj = ResourceManager.GetObject("ccStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   # MDPlayer
        ///VGMファイルなどのPlayer(メガドライブ音源チップなどのエミュレーションによる演奏ツール)  
        ///  
        ///[概要]  
        ///  このツールは、鍵盤表示を行いながらVGMファイルの再生を行います。  
        ///  (NRD,XGM,S98,MID,RCP,NSF,HES,SID,MDR,MDX,MND,MUC(TBD),MUB(TBD)ファイルにも対応。)  
        ///  
        ///[注意]  
        ///  ・再生時の音量に注意してください。バグによる雑音が大音量で再生される場合もあります。  
        ///  (特に再生したことのないファイルを試す場合や、プログラムを更新した場合。)  
        ///  
        ///  ・使用中に不具合を見つけた場合はお手数ですがTwitter(@kumakumakumaT_T)までご連絡ください。  
        ///  (VGMPlayやNRTDRV、その他素晴らしいソフトウェアの作者様方に、  
        ///  直接MDPlayerについての連絡がいくことの無い様にお願いします。)  
        ///  できるかぎり対応させていただくつもりですが、ご希望に添えないことも多々あります。ご了承ください。  
        ///  
        ///[対応フォーマ [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string cntDescription {
            get {
                return ResourceManager.GetString("cntDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   例外発生:\r\n- Type ------\r\n{0}\r\n- Message ------\r\n{1}\r\n- Source ------\r\n{2}\r\n- StackTrace ------\r\n{3}\r\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string cntExceptionFormat {
            get {
                return ResourceManager.GetString("cntExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内部例外:\r\n- Type ------\r\n{0}\r\n- Message ------\r\n{1}\r\n- Source ------\r\n{2}\r\n- StackTrace ------\r\n{3}\r\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string cntInnerExceptionFormat {
            get {
                return ResourceManager.GetString("cntInnerExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   log.txt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string cntLogFilename {
            get {
                return ResourceManager.GetString("cntLogFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string cntSettingFileName {
            get {
                return ResourceManager.GetString("cntSettingFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VGMファイル(*.vgm;*.vgz)|*.vgm;*.vgz|
        ///NRDファイル(*.nrd)|*.nrd|
        ///XGMファイル(*.xgm)|*.xgm|
        ///ZGMファイル(*.zgm)|*.zgm|
        ///S98ファイル(*.s98)|*.s98|
        ///NSFファイル(*.nsf)|*.nsf|
        ///HESファイル(*.hes)|*.hes|
        ///SIDファイル(*.sid)|*.sid|
        ///MNDファイル(*.mnd)|*.mnd|
        ///MDRファイル(*.mdr)|*.mdr|
        ///MDXファイル(*.mdx)|*.mdx|
        ///MUCOM88ファイル(*.mub;*.muc)|*.mub;*.muc|
        ///PMDファイル(*.m;*.m2;*.mz;*.mml)|*.m;*.m2;*.mz;*.mml|
        ///StandardMIDIファイル(*.mid)|*.mid|
        ///RCPファイル(*.rcp)|*.rcp|
        ///M3Uファイル(*.m3u)|*.m3u|
        ///アーカイブファイル(*.zip;*.lzh)|*.zip;*.lzh|
        ///すべてのサポートファイル(*.vgm;*.vgz;*.zip;*.lzh;*.nrd [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string cntSupportFile {
            get {
                return ResourceManager.GetString("cntSupportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yyyy/MM/dd HH:mm:ss     に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string cntTimeFormat {
            get {
                return ResourceManager.GetString("cntTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
        ///  &lt;YM2612Volume&gt;-192&lt;/YM2612Volume&gt;
        ///  &lt;SN76489Volume&gt;-192&lt;/SN76489Volume&gt;
        ///  &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
        ///  &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
        ///  &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
        ///  &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
        ///  &lt;OKIM6258Volume&gt;-192&lt;/OKIM6258Volume&gt;
        ///  &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
        ///  &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCM [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultVolumeBalance_HES {
            get {
                return ResourceManager.GetString("DefaultVolumeBalance_HES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
        ///  &lt;YM2612Volume&gt;-192&lt;/YM2612Volume&gt;
        ///  &lt;SN76489Volume&gt;-192&lt;/SN76489Volume&gt;
        ///  &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
        ///  &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
        ///  &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
        ///  &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
        ///  &lt;OKIM6258Volume&gt;-192&lt;/OKIM6258Volume&gt;
        ///  &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
        ///  &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCM [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultVolumeBalance_MDR {
            get {
                return ResourceManager.GetString("DefaultVolumeBalance_MDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
        ///  &lt;YM2612Volume&gt;-192&lt;/YM2612Volume&gt;
        ///  &lt;SN76489Volume&gt;-192&lt;/SN76489Volume&gt;
        ///  &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
        ///  &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
        ///  &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
        ///  &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
        ///  &lt;OKIM6258Volume&gt;0&lt;/OKIM6258Volume&gt;
        ///  &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
        ///  &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCMVol [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultVolumeBalance_MDX {
            get {
                return ResourceManager.GetString("DefaultVolumeBalance_MDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
        ///  &lt;YM2612Volume&gt;-192&lt;/YM2612Volume&gt;
        ///  &lt;SN76489Volume&gt;-192&lt;/SN76489Volume&gt;
        ///  &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
        ///  &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
        ///  &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
        ///  &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
        ///  &lt;OKIM6258Volume&gt;0&lt;/OKIM6258Volume&gt;
        ///  &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
        ///  &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCMVol [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultVolumeBalance_MND {
            get {
                return ResourceManager.GetString("DefaultVolumeBalance_MND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
        ///  &lt;YM2612Volume&gt;-192&lt;/YM2612Volume&gt;
        ///  &lt;SN76489Volume&gt;-192&lt;/SN76489Volume&gt;
        ///  &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
        ///  &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
        ///  &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
        ///  &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
        ///  &lt;OKIM6258Volume&gt;-192&lt;/OKIM6258Volume&gt;
        ///  &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
        ///  &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCM [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultVolumeBalance_MUB {
            get {
                return ResourceManager.GetString("DefaultVolumeBalance_MUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
        ///  &lt;YM2612Volume&gt;-192&lt;/YM2612Volume&gt;
        ///  &lt;SN76489Volume&gt;-192&lt;/SN76489Volume&gt;
        ///  &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
        ///  &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
        ///  &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
        ///  &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
        ///  &lt;OKIM6258Volume&gt;-192&lt;/OKIM6258Volume&gt;
        ///  &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
        ///  &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCM [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultVolumeBalance_MUC {
            get {
                return ResourceManager.GetString("DefaultVolumeBalance_MUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
        ///  &lt;YM2612Volume&gt;-192&lt;/YM2612Volume&gt;
        ///  &lt;SN76489Volume&gt;-192&lt;/SN76489Volume&gt;
        ///  &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
        ///  &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
        ///  &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
        ///  &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
        ///  &lt;OKIM6258Volume&gt;-192&lt;/OKIM6258Volume&gt;
        ///  &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
        ///  &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCM [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultVolumeBalance_NRT {
            get {
                return ResourceManager.GetString("DefaultVolumeBalance_NRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
        ///  &lt;YM2612Volume&gt;-192&lt;/YM2612Volume&gt;
        ///  &lt;SN76489Volume&gt;-192&lt;/SN76489Volume&gt;
        ///  &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
        ///  &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
        ///  &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
        ///  &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
        ///  &lt;OKIM6258Volume&gt;-192&lt;/OKIM6258Volume&gt;
        ///  &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
        ///  &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCM [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultVolumeBalance_NSF {
            get {
                return ResourceManager.GetString("DefaultVolumeBalance_NSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
        ///  &lt;YM2612Volume&gt;0&lt;/YM2612Volume&gt;
        ///  &lt;SN76489Volume&gt;-192&lt;/SN76489Volume&gt;
        ///  &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
        ///  &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
        ///  &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
        ///  &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
        ///  &lt;OKIM6258Volume&gt;-192&lt;/OKIM6258Volume&gt;
        ///  &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
        ///  &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCMVol [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultVolumeBalance_S98 {
            get {
                return ResourceManager.GetString("DefaultVolumeBalance_S98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
        ///  &lt;YM2612Volume&gt;-192&lt;/YM2612Volume&gt;
        ///  &lt;SN76489Volume&gt;-192&lt;/SN76489Volume&gt;
        ///  &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
        ///  &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
        ///  &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
        ///  &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
        ///  &lt;OKIM6258Volume&gt;-192&lt;/OKIM6258Volume&gt;
        ///  &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
        ///  &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCM [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultVolumeBalance_SID {
            get {
                return ResourceManager.GetString("DefaultVolumeBalance_SID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
        ///  &lt;YM2612Volume&gt;0&lt;/YM2612Volume&gt;
        ///  &lt;SN76489Volume&gt;0&lt;/SN76489Volume&gt;
        ///  &lt;RF5C68Volume&gt;0&lt;/RF5C68Volume&gt;
        ///  &lt;RF5C164Volume&gt;0&lt;/RF5C164Volume&gt;
        ///  &lt;PWMVolume&gt;0&lt;/PWMVolume&gt;
        ///  &lt;C140Volume&gt;0&lt;/C140Volume&gt;
        ///  &lt;OKIM6258Volume&gt;0&lt;/OKIM6258Volume&gt;
        ///  &lt;OKIM6295Volume&gt;0&lt;/OKIM6295Volume&gt;
        ///  &lt;SEGAPCMVolume&gt;0&lt;/SEGAPCMVolume&gt;
        ///  &lt;AY8910Volume&gt;0&lt; [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultVolumeBalance_VGM {
            get {
                return ResourceManager.GetString("DefaultVolumeBalance_VGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
        ///  &lt;YM2612Volume&gt;0&lt;/YM2612Volume&gt;
        ///  &lt;SN76489Volume&gt;-15&lt;/SN76489Volume&gt;
        ///  &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
        ///  &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
        ///  &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
        ///  &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
        ///  &lt;OKIM6258Volume&gt;-192&lt;/OKIM6258Volume&gt;
        ///  &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
        ///  &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCMVolu [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultVolumeBalance_XGM {
            get {
                return ResourceManager.GetString("DefaultVolumeBalance_XGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Balance xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;MasterVolume&gt;0&lt;/MasterVolume&gt;
        ///  &lt;YM2612Volume&gt;0&lt;/YM2612Volume&gt;
        ///  &lt;SN76489Volume&gt;-15&lt;/SN76489Volume&gt;
        ///  &lt;RF5C68Volume&gt;-192&lt;/RF5C68Volume&gt;
        ///  &lt;RF5C164Volume&gt;-192&lt;/RF5C164Volume&gt;
        ///  &lt;PWMVolume&gt;-192&lt;/PWMVolume&gt;
        ///  &lt;C140Volume&gt;-192&lt;/C140Volume&gt;
        ///  &lt;OKIM6258Volume&gt;-192&lt;/OKIM6258Volume&gt;
        ///  &lt;OKIM6295Volume&gt;-192&lt;/OKIM6295Volume&gt;
        ///  &lt;SEGAPCMVolume&gt;-192&lt;/SEGAPCMVolu [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DefaultVolumeBalance_ZGM {
            get {
                return ResourceManager.GetString("DefaultVolumeBalance_ZGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap downPL {
            get {
                object obj = ResourceManager.GetObject("downPL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap FeliAndMD2 {
            get {
                object obj = ResourceManager.GetObject("FeliAndMD2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap imgPL {
            get {
                object obj = ResourceManager.GetObject("imgPL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap japPL {
            get {
                object obj = ResourceManager.GetObject("japPL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap mmlPL {
            get {
                object obj = ResourceManager.GetObject("mmlPL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap openPL {
            get {
                object obj = ResourceManager.GetObject("openPL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap plane {
            get {
                object obj = ResourceManager.GetObject("plane", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeAY8910 {
            get {
                object obj = ResourceManager.GetObject("planeAY8910", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeB {
            get {
                object obj = ResourceManager.GetObject("planeB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeC {
            get {
                object obj = ResourceManager.GetObject("planeC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeC352 {
            get {
                object obj = ResourceManager.GetObject("planeC352", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeControl {
            get {
                object obj = ResourceManager.GetObject("planeControl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeD {
            get {
                object obj = ResourceManager.GetObject("planeD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeE {
            get {
                object obj = ResourceManager.GetObject("planeE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeF {
            get {
                object obj = ResourceManager.GetObject("planeF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeFDS {
            get {
                object obj = ResourceManager.GetObject("planeFDS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeHuC6280 {
            get {
                object obj = ResourceManager.GetObject("planeHuC6280", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeK051649 {
            get {
                object obj = ResourceManager.GetObject("planeK051649", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeMIDI_GM {
            get {
                object obj = ResourceManager.GetObject("planeMIDI_GM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeMIDI_GS {
            get {
                object obj = ResourceManager.GetObject("planeMIDI_GS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeMIDI_XG {
            get {
                object obj = ResourceManager.GetObject("planeMIDI_XG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeMixer {
            get {
                object obj = ResourceManager.GetObject("planeMixer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeMMC5 {
            get {
                object obj = ResourceManager.GetObject("planeMMC5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeMSM6258 {
            get {
                object obj = ResourceManager.GetObject("planeMSM6258", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeMSM6295 {
            get {
                object obj = ResourceManager.GetObject("planeMSM6295", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeMultiPCM {
            get {
                object obj = ResourceManager.GetObject("planeMultiPCM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeN106 {
            get {
                object obj = ResourceManager.GetObject("planeN106", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeNESDMC {
            get {
                object obj = ResourceManager.GetObject("planeNESDMC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planePPZ8 {
            get {
                object obj = ResourceManager.GetObject("planePPZ8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeQSound {
            get {
                object obj = ResourceManager.GetObject("planeQSound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeSEGAPCM {
            get {
                object obj = ResourceManager.GetObject("planeSEGAPCM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeSN76489 {
            get {
                object obj = ResourceManager.GetObject("planeSN76489", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeVRC6 {
            get {
                object obj = ResourceManager.GetObject("planeVRC6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeVRC7 {
            get {
                object obj = ResourceManager.GetObject("planeVRC7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeY8950 {
            get {
                object obj = ResourceManager.GetObject("planeY8950", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeYM2203 {
            get {
                object obj = ResourceManager.GetObject("planeYM2203", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeYM2413 {
            get {
                object obj = ResourceManager.GetObject("planeYM2413", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeYM2610 {
            get {
                object obj = ResourceManager.GetObject("planeYM2610", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeYM2612 {
            get {
                object obj = ResourceManager.GetObject("planeYM2612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeYM2612MIDI {
            get {
                object obj = ResourceManager.GetObject("planeYM2612MIDI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeYM3526 {
            get {
                object obj = ResourceManager.GetObject("planeYM3526", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeYM3812 {
            get {
                object obj = ResourceManager.GetObject("planeYM3812", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeYMF262 {
            get {
                object obj = ResourceManager.GetObject("planeYMF262", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeYMF278B {
            get {
                object obj = ResourceManager.GetObject("planeYMF278B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeYMZ280B {
            get {
                object obj = ResourceManager.GetObject("planeYMZ280B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rChipName_01 {
            get {
                object obj = ResourceManager.GetObject("rChipName_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rChipName_02 {
            get {
                object obj = ResourceManager.GetObject("rChipName_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rChipName_03 {
            get {
                object obj = ResourceManager.GetObject("rChipName_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] README {
            get {
                object obj = ResourceManager.GetObject("README", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rFader {
            get {
                object obj = ResourceManager.GetObject("rFader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rFont_01 {
            get {
                object obj = ResourceManager.GetObject("rFont_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rFont_02 {
            get {
                object obj = ResourceManager.GetObject("rFont_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rFont_03 {
            get {
                object obj = ResourceManager.GetObject("rFont_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rFont_04 {
            get {
                object obj = ResourceManager.GetObject("rFont_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rFont_05 {
            get {
                object obj = ResourceManager.GetObject("rFont_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rFont_06 {
            get {
                object obj = ResourceManager.GetObject("rFont_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rKakko_00 {
            get {
                object obj = ResourceManager.GetObject("rKakko_00", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rKBD_01 {
            get {
                object obj = ResourceManager.GetObject("rKBD_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rKBD_02 {
            get {
                object obj = ResourceManager.GetObject("rKBD_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rKBD_03 {
            get {
                object obj = ResourceManager.GetObject("rKBD_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMenuButtons_01 {
            get {
                object obj = ResourceManager.GetObject("rMenuButtons_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMenuButtons_02 {
            get {
                object obj = ResourceManager.GetObject("rMenuButtons_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMIDILCD_01 {
            get {
                object obj = ResourceManager.GetObject("rMIDILCD_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMIDILCD_02 {
            get {
                object obj = ResourceManager.GetObject("rMIDILCD_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMIDILCD_03 {
            get {
                object obj = ResourceManager.GetObject("rMIDILCD_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMIDILCD_Fader_01 {
            get {
                object obj = ResourceManager.GetObject("rMIDILCD_Fader_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMIDILCD_Fader_02 {
            get {
                object obj = ResourceManager.GetObject("rMIDILCD_Fader_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMIDILCD_Fader_03 {
            get {
                object obj = ResourceManager.GetObject("rMIDILCD_Fader_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMIDILCD_Font_01 {
            get {
                object obj = ResourceManager.GetObject("rMIDILCD_Font_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMIDILCD_Font_02 {
            get {
                object obj = ResourceManager.GetObject("rMIDILCD_Font_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMIDILCD_Font_03 {
            get {
                object obj = ResourceManager.GetObject("rMIDILCD_Font_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMIDILCD_Font_04 {
            get {
                object obj = ResourceManager.GetObject("rMIDILCD_Font_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMIDILCD_Font_05 {
            get {
                object obj = ResourceManager.GetObject("rMIDILCD_Font_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMIDILCD_Font_06 {
            get {
                object obj = ResourceManager.GetObject("rMIDILCD_Font_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMIDILCD_KBD_01 {
            get {
                object obj = ResourceManager.GetObject("rMIDILCD_KBD_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMIDILCD_Vol_01 {
            get {
                object obj = ResourceManager.GetObject("rMIDILCD_Vol_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMIDILCD_Vol_02 {
            get {
                object obj = ResourceManager.GetObject("rMIDILCD_Vol_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMIDILCD_Vol_03 {
            get {
                object obj = ResourceManager.GetObject("rMIDILCD_Vol_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rNESDMC {
            get {
                object obj = ResourceManager.GetObject("rNESDMC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rPan_01 {
            get {
                object obj = ResourceManager.GetObject("rPan_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rPan_02 {
            get {
                object obj = ResourceManager.GetObject("rPan_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rPan_03 {
            get {
                object obj = ResourceManager.GetObject("rPan_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rPan2_01 {
            get {
                object obj = ResourceManager.GetObject("rPan2_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rPan2_02 {
            get {
                object obj = ResourceManager.GetObject("rPan2_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rPSGEnv {
            get {
                object obj = ResourceManager.GetObject("rPSGEnv", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rPSGMode_01 {
            get {
                object obj = ResourceManager.GetObject("rPSGMode_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rPSGMode_02 {
            get {
                object obj = ResourceManager.GetObject("rPSGMode_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rPSGMode_03 {
            get {
                object obj = ResourceManager.GetObject("rPSGMode_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rPSGMode_04 {
            get {
                object obj = ResourceManager.GetObject("rPSGMode_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rPSGMode_05 {
            get {
                object obj = ResourceManager.GetObject("rPSGMode_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rPSGMode_06 {
            get {
                object obj = ResourceManager.GetObject("rPSGMode_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rType_01 {
            get {
                object obj = ResourceManager.GetObject("rType_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rType_02 {
            get {
                object obj = ResourceManager.GetObject("rType_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rType_03 {
            get {
                object obj = ResourceManager.GetObject("rType_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rType_04 {
            get {
                object obj = ResourceManager.GetObject("rType_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rType_05 {
            get {
                object obj = ResourceManager.GetObject("rType_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rType_06 {
            get {
                object obj = ResourceManager.GetObject("rType_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rVol_01 {
            get {
                object obj = ResourceManager.GetObject("rVol_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rVol_02 {
            get {
                object obj = ResourceManager.GetObject("rVol_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rVol_03 {
            get {
                object obj = ResourceManager.GetObject("rVol_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rWavGraph {
            get {
                object obj = ResourceManager.GetObject("rWavGraph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rWavGraph2 {
            get {
                object obj = ResourceManager.GetObject("rWavGraph2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap savePL {
            get {
                object obj = ResourceManager.GetObject("savePL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap txtPL {
            get {
                object obj = ResourceManager.GetObject("txtPL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap upPL {
            get {
                object obj = ResourceManager.GetObject("upPL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
